//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AjaxCab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverLocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DriverLocation()
        {
            this.BookingDetails = new HashSet<BookingDetail>();
        }
    
        public int DriverMappingId { get; set; }
        public Nullable<int> DriverId { get; set; }
        public Nullable<int> DriverLocationId { get; set; }
        public string Avaliablity { get; set; }
        public Nullable<int> balanceAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingDetail> BookingDetails { get; set; }
    }
}
