//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace new_cab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingDetail
    {
        public int BookingId { get; set; }
        public Nullable<int> UserMappingId { get; set; }
        public Nullable<int> Charge { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public Nullable<System.DateTime> BookingTime { get; set; }
        public Nullable<int> cancelBooking { get; set; }
        public Nullable<int> driverId { get; set; }
        public Nullable<int> tripStatus { get; set; }
        public Nullable<int> userid { get; set; }
    
        public virtual DriverLocation DriverLocation { get; set; }
    }
}
