//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace new_cab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class companyProfit
    {
        public int id { get; set; }
        public Nullable<int> bookingid { get; set; }
        public Nullable<int> profit { get; set; }
    }
}
