//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AjaxCab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class logindetail
    {
        public int loginid { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> otp { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
    }
}
